apiVersion: v1
kind: ServiceAccount
metadata:
  name: controller
  namespace: web3cache

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: web3cache
  name: deployment-controller
rules:
  - apiGroups: ["", "apps"]
    resources: ["pods", "deployments"]
    verbs: ["get", "list", "create", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deployment-controller-binding
  namespace: web3cache
subjects:
  - kind: ServiceAccount
    name: controller
    namespace: web3cache
roleRef:
  kind: Role
  name: deployment-controller
  apiGroup: rbac.authorization.k8s.io