apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: web3cache-controller
  namespace: web3cache
spec:
  secretObjects:
    - secretName: dockerconfigjson-github-com
      type: kubernetes.io/dockerconfigjson
      data:
        - objectName: dockerauthtoken
          key: ".dockerconfigjson"
    - secretName: controller-secrets
      type: Opaque
      data:
        - objectName: MONGOURI
          key: MONGOURI
        - objectName: READAPIKEY
          key: READAPIKEY
  provider: aws
  parameters:
    objects: |
      - objectName: "prod/web3cache"
        objectType: "secretsmanager"
        jmesPath:
          - path: '"docker-auth-token"'
            objectAlias: dockerauthtoken
          - path: MONGOURI_SUBSCRIPTIONS
            objectAlias: MONGOURI
          - path: READAPIKEY
            objectAlias: READAPIKEY
